spring.application.name=demo

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Rightsy
spring.datasource.username=postgres
spring.datasource.password=Random123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# security things

jwt.secretKey=jkh312jkh34gh1ji432gh43jhjkl4132hjk14hjk1h4jk1h24jk1ho;j13yh


# Admin Details

admin.name=systemAdmin
admin.password=SyStem@dmin123
admin.email=admin@Rightsy.com